### ISSUE TITLE
Change field group indicator in sidebar/nav

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#14]
Rather than using an arrow, switch to a plus sign / "x". When expanded, the plus sign rotates 45° to be an "x". When collapsed the opposite happens.

Default is expanded.

**Comment by erikreagan** [comment]
@alexsailer @andyfought A thought for you: we use an "x" in the sidebar to _collapse_ but we use an "x" in the header area to _delete_. It's not a huge deal right now, but long-term I think it's worth considering a change to one of these to avoid confusion.

http://d.pr/i/18fEK

Thoughts?

**Comment by alexsailer** [comment]
go back to an arrow? ;)

**Comment by erikreagan** [comment]
@alexsailer that's what I was thinking haha.

@andyfought thoughts? Maybe an arrow pointing right for collapsed and pointing down for expanded?

**Comment by andyfought** [comment]
I don't like the arrows, and it is in a completely different context to get confused in my opinion

**Comment by andyfought** [comment]
Maybe for this we could just use a "+" and "-" as indicators? thoughts? @erikreagan @alexsailer

**Comment by erikreagan** [comment]
@andyfought Yeah, I like that.
