### ISSUE TITLE
Define ::selection property for code blocks

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#15]
Looks like Prism sets a couple of properties for `::selection` selectors but the browser (Chrome at least) reads that as removing the background color. So selecting text in code blocks looks like you aren't selecting text right now.

![image](https://cloud.githubusercontent.com/assets/58048/7219681/a2f6ad7c-e679-11e4-8cb0-5a5b4296449d.png)

Let's define a color (or colors) for `::selection`. We can just have one color or we can get fancy schmancy and have different colors for different prism tokens.

@alexsailer suggestions on color(s)? @andyfought I'm assigning to you to implement.

**Comment by andyfought** [comment]
I like the way that yellow looks. Should I do that? @erikreagan

**Comment by erikreagan** [comment]
@andyfought I already added that actually.
@alexsailer you good with it?

**Comment by alexsailer** [comment]
Yea I dig it

**Comment by erikreagan** [comment]
Cool. I'll close the issue since the code is already there then.
