### ISSUE TITLE
Style for paragraph text at the bottom of Field sections

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#16]
Sometimes there might be a block of text after the entire set of code blocks for a Field (as opposed to per-code block which was recently defined+implemented).

@alexsailer any thoughts on what this could/should look like? Here's a sample:

![image](https://cloud.githubusercontent.com/assets/58048/7219814/ccf65e64-e67f-11e4-9483-76af1d715d86.png)

**Comment by andyfought** [comment]
I think this looks good, maybe tone down the yellow a bit though?

**Comment by erikreagan** [comment]
@andyfought @alexsailer how about this?

![image](https://cloud.githubusercontent.com/assets/58048/7265810/c03f9358-e86d-11e4-9871-c1875ccf2802.png)

**Comment by alexsailer** [comment]
@erikreagan definitely better.

**Comment by erikreagan** [comment]
@alexsailer sweet, thanks. gonna mark this one done.
