### ISSUE TITLE
Add a "no results" view when the filter returns nothing

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#17]
Sometimes a person might search for a field and get no results. Either they misspelled it, or the field just doesn't exist, or something else I suppose. Let's build in a view to show them that there are no results. Something quirky.

Example:

![image](https://cloud.githubusercontent.com/assets/58048/7219828/d4201f4e-e680-11e4-9710-6ec6e2606829.png)

**Comment by erikreagan** [comment]
@alexsailer ping. any thoughts on this or is it good to go?

**Comment by alexsailer** [comment]
@erikreagan I think it's fine for right now but I'd like to do a custom illustration/animated gif at some point

**Comment by erikreagan** [comment]
@alexsailer Okay cool. I'll leave that to you to schedule and do whenever you want. For now I'll close this issue and we can talk about better/cooler ideas when you're ready. Thanks!
