### ISSUE TITLE
Typo in Plain Text code snippet

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#19]
The "If Exists" Conditional heading is missing the opening quote.

![image](https://cloud.githubusercontent.com/assets/58048/7222204/fef37d1e-e6d6-11e4-8e58-9763841b89df.png)

(Thanks for the catch @lindseydiloreto)

**Comment by lindseydiloreto** [comment]
You're very welcome! :)
