### ISSUE TITLE
Create logic for initially expanded field groups

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#2]
What should the behavior be for field groups when the page first loads? Are they all expanded? Collapsed? Just 1 expanded?

![image](https://cloud.githubusercontent.com/assets/58048/7195511/e2430378-e48e-11e4-9abb-bfeeb5b7d0a8.png)

**Comment by erikreagan** [comment]
@alexsailer quick ping here as well. the groups default to open/expanded. sound good to you?

**Comment by alexsailer** [comment]
@erikreagan sounds perfect.

**Comment by erikreagan** [comment]
:+1:
