### ISSUE TITLE
Custom Elements creation error

### ISSUE THREAD

**Issue by Natetronn** [focuslabllc/craft-field-cheat-sheet#23]
When creating a custom element I get the following error:

![Error](https://monosnap.com/file/pE2R1a59jXa4E5Wgil5bvERBSzXbBi.png)

You have an animated GIF in your readme showing this actually working correctly. When I, however, add a custom element name it creates it but, the input is left with the name still sitting there (custom in my example) and the error above show up in the console.

This is in Chrome Version 42.0.2311.90 (64-bit) on MAC OX 10.10.3

Let me know if there is any other info which will help with debugging this.

**Comment by erikreagan** [comment]
@Natetronn Bug confirmed. I'll work out a patch in the next day. Thanks!

**Comment by erikreagan** [comment]
@Natetronn This one is patched up and ready for a new download. Thanks for reporting it!
