### ISSUE TITLE
Fresh Install Error - Fresh Craft CMS Installation

### ISSUE THREAD

**Issue by nexflo** [focuslabllc/craft-field-cheat-sheet#25]
( ! ) Fatal error: Maximum function nesting level of '100' reached, aborting! in /Users/fw/Sites/craft/craft/app/vendor/twig/twig/lib/Twig/Node.php on line 192

**Comment by erikreagan** [comment]
@nexflo This is likely an xDebug setting at play. Try bumping up your limit from 100 to something higher. Others have seen this and this change has resolved the problem.
