### ISSUE TITLE
Replace underscores with spaces

### ISSUE THREAD

**Issue by lindseydiloreto** [focuslabllc/craft-field-cheat-sheet#27]
When parsing out a field type's name, the parser does a great job of splitting camelCase words and putting spaces in there!

However, it doesn't do the same for **underscores**, leading to some weird formatting for 3rd party field types...

![screen shot 2015-04-19 at 11 25 18 pm](https://cloud.githubusercontent.com/assets/5309692/7224810/02c38af0-e6ec-11e4-9b3d-a0f80b64dd68.png)

Would it be possible to fix that?

**Comment by erikreagan** [comment]
@lindseydiloreto I tried coming at this from a regex perspective, but couldn't get it working. Can you try something for me? In your `cheatsheet.html` file go to [~ line 196](https://github.com/focuslabllc/craft-field-cheat-sheet/blob/master/downloads/cheatsheet.html#L196) and replace it with this:

```<span class="field_type">{{ field.type|replace('_', '')|replace('/(.)([A-Z])/', '$1 $2')|title }}</span>```

It's running through multiple filters but seems to get the job done in a quick test of mine. If it works for you as well, I'll add this patch in.

I was hoping to use Craft's support for [multiple regex patterns](http://buildwithcraft.com/docs/templating/filters#replace) but for whatever reason I couldn't get that to work. I plan to dig into the internals to find out why.

**Comment by lindseydiloreto** [comment]
Works like a charm!

Assuming the plugin dev has properly capitalized the first letter after the underscore, this should work flawlessly. Though I'm sure there are some folks who have (intentionally or accidentally) used a lowercase letter after their underscore.

Maybe just replace the underscore with a space? That should also work, in theory, and still cover any folks using a lowercase letter:

    replace('_', ' ')

**Comment by erikreagan** [comment]
Yeah, I played around with removing the character and replacing it with a space. Couldn't decide. You've swayed my opinion though. Good point about some people not sticking to naming standards. I'll go with replacing it with a space.

This will be implemented in a release soon. Thanks!

**Comment by lindseydiloreto** [comment]
Np, thanks for patching that! :)
