### ISSUE TITLE
Complete Table code samples

### ISSUE THREAD

**Issue by erikreagan** [focuslabllc/craft-field-cheat-sheet#29]

**Comment by erikreagan** [comment]
@alexsailer The final 2 field types I have to implement are the ones that are "different" in terms of output. This one is simply called Table and it allows for flexible table creation. I want to show a table with 3 columns that contain data about each "Table field."

Can you put together a table design and throw a screenshot in here so @andyfought can mark it up?

**Comment by erikreagan** [comment]
The table would contain a header row, then body rows containing plain text and single-line code samples.

First Heading | Second Heading | Third Heading
----------- | ----------- | -----------
Text | `{{ code }}` | text
Text | `{{ code }}` | text
Text | `{{ code }}` | text

This is how GitHub styles that kinda stuff.

**Comment by alexsailer** [comment]
![screenshot 2015-04-23 10 53 42](https://cloud.githubusercontent.com/assets/4948316/7300163/8edc8866-e9a8-11e4-873a-e9ef8932f252.png)

**Comment by erikreagan** [comment]
Schweet. Probably no need for any changes, but for @andyfought's notes:

1. The descriptive text will never be above it like that
2. No copy-to-clipboard icon needed

**Comment by andyfought** [comment]
On it!

**Comment by andyfought** [comment]
Should be good to go. Please confirm and we can close this issue.

**Comment by erikreagan** [comment]
@andyfought pulling down to check it out soon. Thanks!
