### ISSUE TITLE
Switch/case syntax is incorrect in the matrix example

### ISSUE THREAD

**Issue by angusfretwell** [focuslabllc/craft-field-cheat-sheet#33]
The syntax `{% case="condition" %}` throws an error; it should be `{% case "condition" %}`.

**Comment by erikreagan** [comment]
Hi @angusfretwell. Great catch. I'd love to merge this in but it looks like the pull request you created was to the master branch on your own repo. If you send it over to this repo I'll merge it in.

Thanks!
Erik
