### ISSUE TITLE
Have issues running with PHP5.5.21-1

### ISSUE THREAD

**Issue by stevieg83** [focuslabllc/craft-field-cheat-sheet#35]
I've got a Vagrant/Puphet config and cheatsheet fails with

`Fatal error: Maximum function nesting level of '100' reached, aborting! in /var/www/craft/app/vendor/twig/twig/lib/Twig/Node.php on line 192`

I did notice the same thing with MAMP Pro running PHP 5.5.23 but no problems on 5.4.39

**Comment by erikreagan** [comment]
Hey Steven,

Check out #25 for more info. Should be an easy fix.

—e

**Comment by stevieg83** [comment]
Doh! I should have have looked at closed issues. Thanks man.
