### ISSUE TITLE
Avast! Thar be letter 'C' Pirates in these here waters!

### ISSUE THREAD

**Issue by proimage** [focuslabllc/craft-field-cheat-sheet#37]
The JS that intercepts the "C" keypress and focuses the "Enter Custom Element" text input ignores the CTRL state (Windows 10 & Chrome), thus triggering even on `CTRL+C`. While the text copy still takes place, the cursor jumps into the text field and the entire window scrolls back up to the top. Shiver me timbers!

**Comment by tjhill** [comment]
I also have this issue on mac w/ chrome (cmd-C) - I've just started using this and love it, apart from this bug!

**Comment by rostockahoi** [comment]
You're right. This is annoying. I'm on Linux + Firefox 51 dev.

**Comment by erikreagan** [comment]
@proimage @hill @rostockahoi This is fixed up with the latest release. Thanks!
