### ISSUE TITLE
Deprecation error: getBuild() has been deprecated

### ISSUE THREAD

**Issue by SimonEast** [focuslabllc/craft-field-cheat-sheet#40]
I noticed I'm now getting the following deprecation warning when running the cheat-sheet:

> craft()->getBuild() has been deprecated. As of Craft 2.6.2951, craft()->getVersion() returns the complete version number (X.Y.Z).	/home/staging7/public_html/ku/craft/templates/cheatsheet.html

I suspect it's a simple fix to update the template to use `getVersion()` although I don't think it will be backwards-compatible.

Simon.

**Comment by erikreagan** [comment]
Hey Simon,

We're getting it too. :)

We're on a holiday break right now but have plans to roll out a fix in the
first week of January. Thanks for posting it here to make sure we were
aware! I'll reply again when this is fixed up.

Erik

**Comment by erikreagan** [comment]
@SimonEast This should be all fixed up with the latest release. :)
